[package]
name = "merit"
version = "0.0.1"
authors = ["Sean McArthur <sean.monstar@gmail.com>"]

[dependencies]
env_logger = "*"
rustc-serialize = "*"

[dependencies.hyper]
version = "0.3"
features = ["nightly"]
