[package]
name = "merit"
version = "0.0.1"
authors = ["Sean McArthur <sean.monstar@gmail.com>"]

[dependencies]
rustc-serialize = "*"

[dependencies.hyper]
git = "https://github.com/hyperium/hyper"
features = ["nightly"]
